firmware(libosmocore): add missing 'if !EMBEDDED'
Fix compilation with GCC 14.2, which otherwise fails with errors like:

../../src/utils.c:49:22: error: implicit declaration of function 'strcasecmp' [-Wimplicit-function-declaration]

Change-Id: Ia7fdd5edd5edd1ee126dfbcaa75b3d988143f2e1