trxcon: fixup: handle DATA.cnf/TRAFFIC.cnf via TRXCON_EV_TX_DATA_CNF
Found this problem while trying to build with "-flto":

  ../include/osmocom/bb/trxcon/l1ctl.h:21:5: error: type of
        'l1ctl_tx_dt_conf' does not match original declaration
  [-Werror=lto-type-mismatch]
     21 | int l1ctl_tx_dt_conf(struct l1ctl_client *l1c,
        |     ^
  l1ctl.c:288:5: note: type mismatch in parameter 2
    288 | int l1ctl_tx_dt_conf(struct l1ctl_client *l1c, bool traffic,
        |     ^

The trxcon_fsm is passing only two arguments to l1ctl_tx_dt_conf().
The 'traffic' flag is included in struct trxcon_param_tx_data_cnf,
so the 2rd argument is not needed and should have been removed.

Change-Id: Ifc538f940571172fa237ecb7000f3cfea3655edc