firmware(libosmocore): update function header
Update the function header to be the same as in
target/firmware/include/string.h, so it compiles successfully with
GCC 14.2. Otherwise:

  lib/strcmp.c:5:1: error: return type defaults to 'int' [-Wimplicit-int]
      5 | strcmp(s1, s2)
        | ^~~~~~

Change-Id: Ic601d84c3366d9aec661663c80ba9d7586510d63