firmware: string: import strrchr from linux
Modern libosmocore uses strrchr if the following VTY option is set:
  logging print file basename

Add strrchr to string.c, to fix:
  logging.c:(.text.const_basename+0xc): undefined reference to `strrchr'

Change-Id: I1a8868d6d274e5edb273440fdb7e1394027b7dea